### ISSUE TITLE
The use of aux and weight_predictor

### ISSUE THREAD

**Issue by xiaofeixia2022** [kechunl/AdaCode#5]
Should aux be stored in the second stage? Does the softmax of weight_predictor need to remain false all the time? I saw that the code always sets the softmax of weight_predictor to false. @kechunl

**Comment by kechunl** [comment]
Hi @xiaofeixia2022 , in our experiments, `weight_softmax` is always set as False. We used this flag to study the effect of codebook weight. You can simply set it as False. 

For your first question, could you explain a little bit more? Which aux?

**Comment by xiaofeixia2022** [comment]
Thank you very much for your response! @kechunl  I didn't express myself clearly enough. By 'aux,' I meant the input 'gt_aux' and return value 'aux' in the 'encode_and_decode' function and 'forward' function in the 'adacode_arch.py' and 'adacode_contrast_arch.py' files. I'm not sure if it's functioning properly because I couldn't find what its input should be.

**Comment by kechunl** [comment]
_gt_aux_ and return value _aux_ only enabled in LQ_stage (stage 3). You can find it in https://github.com/kechunl/AdaCode/blob/ecfd33254ffff0881688a0cab33121df4627cf47/basicsr/models/femasr_model.py#L219C10-L226
