### ISSUE TITLE
The weight map

### ISSUE THREAD

**Issue by xiaofeixia2022** [kechunl/AdaCode#6]
Hello Author. I tried multiplying using image features and image prediction weights, but the resulting visualization was very different from the learned weight maps in the paper. I really want to know how you got the weight map in the paper.
![image](https://github.com/kechunl/AdaCode/assets/111624970/e14833ad-2957-4707-8777-268a1772a512)

**Comment by kechunl** [comment]
The weight map visualizations are not the multiplication of weight and image features. They are the outputs directly from the weight predictor.On Jan 8, 2024, at 18:05, xiaofeixia2022 ***@***.***> wrote:﻿
Hello Author. I tried multiplying using image features and image prediction weights, but the resulting visualization was very different from the learned weight maps in the paper. I really want to know how you got the weight map in the paper.
image.png (view on web)
