### ISSUE TITLE
Does the MIT license conflict with CC-BY-NC-SA of FeMaSR?

### ISSUE THREAD

**Issue by RunDevelopment** [kechunl/AdaCode#8]
Hi! I recently wanted to add AdaCode into one of my projects, but I am confused by AdaCode's license.

AdaCode is currently licensed under MIT, but it also says that "This project is based on [FeMaSR](https://github.com/chaofengc/FeMaSR)." As I see it, this is a problem because FeMaSR is licensed under [CC-BY-NC-SA 4.0](https://github.com/chaofengc/FeMaSR/blob/main/LICENSE), which is both non-commercial and copyleft. Since AdaCode is a derivative work of FeMaSR, it should also be licensed under a non-commercial and copyleft license. However, MIT explicitly allows commercial use and is not copyleft, which conflicts with CC-BY-NC-SA 4.0 as I see it.

Is my understanding of this correct? Could you please clarify the license of AdaCode?

Also, if the authors of FeMaSR having given you permission to license AdaCode as MIT, then this is all fine. But it would be nice if you could mention this in the README.

**Comment by kechunl** [comment]
Hi, the license has been modified. Thanks!

**Comment by RunDevelopment** [comment]
Thank you for the quick response!
